var fr_db_queries = [];
fr_db_queries.push('CREATE TABLE fr_keyword_tbl (  id INTEGER,  keyword VARCHAR NOT NULL UNIQUE,  custom INTEGER DEFAULT 1,  PRIMARY KEY (id))');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(1,\'agriculture\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(2,\'excédent\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(3,\'déficit\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(4,\'trésorerie\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(5,\'export\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(6,\'produit intérieur brut\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(7,\'PIB\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(8,\'formation brute de capital\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(9,\'industrie\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(10,\'inflation\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(11,\'revenus\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(12,\'services\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(13,\'fabrication\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(14,\'production d’énergie\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(15,\'population rurale\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(16,\'population urbaine\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(17,\'terres agricoles\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(18,\'CO2\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(19,\'consommation d’électricité\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(20,\'consommation électrique\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(21,\'utilisation d’énergie\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(22,\'surface forestière\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(23,\'assainissement\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(24,\'source d’eau\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(25,\'sources d’eau\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(26,\'eau douce\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(27,\'dette\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(28,\'investissements étrangers\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(29,\'investissement étranger\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(30,\'marchandise\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(31,\'migration nette\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(32,\'aide publique\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(33,\'envois de fonds\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(34,\'envoi de fonds\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(35,\'travailleur\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(36,\'rémunérations des salariés\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(37,\'rémunération des salariés\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(38,\'rémunérations salariales\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(39,\'rémunération salariale\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(40,\'chômage\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(41,\'fertilité chez les adolescents\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(42,\'fertilité adolescente\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(43,\'naissances assistées\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(44,\'naissance assistée\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(45,\'contraception\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(46,\'taux de fécondité\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(47,\'rougeole\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(48,\'part des revenus\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(49,\'espérance de vie\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(50,\'malnutrition\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(51,\'mortalité infantile\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(52,\'SIDA\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(53,\'VIH\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(54,\'école primaire\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(55,\'écoles primaires\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(56,\'écoles secondaires\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(57,\'FMI\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(58,\'fonds monétaire international\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(59,\'chercheur\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(60,\'recherche et développement\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(61,\'R&D\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(62,\'haute technologie\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(63,\'utilisateurs internet\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(64,\'capitalisation boursière\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(65,\'bourse\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(66,\'militaire\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(67,\'dépenses en santé\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(68,\'téléphonie\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(69,\'routes pavées\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(70,\'démarrer une entreprise\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(71,\'RNB\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(72,\'revenu national brut\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(73,\'croissance de la population\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(74,\'population, total\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(75,\'population totale\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(76,\'densité de la population\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(77,\'densité de population\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(78,\'pauvreté\',0)');
fr_db_queries.push('INSERT INTO "fr_keyword_tbl" VALUES(79,\'superficie\',0)');
fr_db_queries.push('CREATE TABLE fr_keyword_to_indicator_tbl (  id INTEGER,  keyword_id INTEGER,   indicator_id INTEGER,  PRIMARY KEY (id),  UNIQUE (keyword_id, indicator_id))');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(1,1,1)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(2,2,4)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(3,3,4)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(4,4,4)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(5,5,5)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(6,6,7)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(7,7,7)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(8,8,10)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(9,9,11)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(10,10,12)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(11,11,13)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(12,12,14)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(13,13,15)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(14,14,16)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(15,15,18)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(16,16,19)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(17,17,2)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(18,18,20)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(19,19,22)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(20,20,22)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(21,21,17)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(22,22,3)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(23,23,23)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(24,24,24)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(25,25,24)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(26,26,25)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(27,27,26)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(28,28,28)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(29,29,28)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(30,30,29)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(31,31,31)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(32,32,32)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(33,33,33)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(34,34,33)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(35,35,33)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(36,36,33)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(37,37,33)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(38,38,33)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(39,39,33)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(40,40,34)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(41,41,35)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(42,42,35)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(43,43,39)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(44,44,39)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(45,45,36)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(46,46,37)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(47,47,40)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(48,48,43)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(49,49,38)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(50,50,41)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(51,51,44)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(52,52,42)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(53,53,42)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(54,54,46)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(55,55,46)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(56,55,47)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(57,56,47)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(58,57,48)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(59,58,48)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(60,59,49)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(61,60,49)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(62,61,49)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(63,62,50)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(64,63,51)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(65,64,54)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(66,65,54)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(67,66,55)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(68,67,56)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(69,68,53)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(70,69,58)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(71,70,59)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(72,71,63)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(73,72,63)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(74,73,64)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(75,74,65)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(76,75,65)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(77,76,66)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(78,77,66)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(79,78,67)');
fr_db_queries.push('INSERT INTO "fr_keyword_to_indicator_tbl" VALUES(80,79,68)');
fr_db_queries.push('CREATE TABLE fr_indicator_name_tbl (  id INTEGER,  indicator_id INTEGER UNIQUE,  indicator_name VARCHAR NOT NULL UNIQUE,  PRIMARY KEY (id))');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(1,1,\'Agriculture, valeur ajoutée (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(2,4,\'Excédent/déficit de trésorerie (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(3,5,\'Exportations de biens et de services (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(4,7,\'PIB ($ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(5,8,\'Croissance du PIB (% annuel)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(6,9,\'PIB par habitant ($ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(7,10,\'Formation brute de capital (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(8,6,\'Importations de biens et de services (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(9,11,\'Industrie, valeur ajoutée (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(10,12,\'Inflation, déflateur du PIB (% annuel)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(11,13,\'Revenus, hors subventions (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(12,14,\'Services, etc. valeur ajoutée (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(13,15,\'Fabrication, valeur ajoutée (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(14,16,\'Production d’énergie (kt d’équivalent pétrole)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(15,18,\'Population rurale (% de la population totale)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(16,19,\'Population urbaine (% du total)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(17,2,\'Terres agricoles (% du territoire)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(18,20,\'Émissions de CO2 (kt)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(19,21,\'Émissions de CO2 (tonnes métriques par habitant)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(20,22,\'Consommation d’électricité (KWh par habitant)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(21,17,\'Utilisation d’énergie (kt d’équivalent pétrole)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(22,3,\'Surface forestière (kilomètres carrés)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(23,23,\'Installations d’assainissement améliorées, en milieu urbain (% de la population urbaine y ayant accès)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(24,24,\'Source d’eau améliorée, en milieu urbain (% de la population urbaine y ayant accès)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(25,25,\'Ressources intérieures renouvelables en eau douce par habitant (mètres cubes)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(26,26,\'Stocks de la dette extérieure, total (Dette en cours et décaissée, $ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(27,28,\'Investissements étrangers directs, entrées nettes (BDP, $ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(28,29,\'Commerce de marchandises (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(29,30,\'Indice des termes de l’échange des marchandises nets (2000=100)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(30,31,\'Migration nette\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(31,32,\'Aide publique au développement nette et aide publique nette reçues ($ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(32,27,\'Service de la dette totale (% des exportations de biens, de services et de revenus)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(33,33,\'Envois de fonds des travailleurs et rémunérations des salariés, reçus ($ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(34,34,\'Chômage, total (% de la population)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(35,35,\'Taux de fertilité chez les adolescents (nombre de naissance par 1 000 femmes âgées de 15 à 19 ans)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(36,39,\'Naissances assistées par du personnel de santé qualifié (% du total)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(37,36,\'Prévalence de la contraception (% des femmes âgées de 15 à 49 ans)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(38,37,\'Taux de fécondité, total (nombre de naissances par femme)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(39,40,\'Immunisation, rougeole (% d’enfants âgés de 12 à 23 mois)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(40,43,\'Part des revenus détenus par les 20% moins élevés\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(41,38,\'Espérance de vie à la naissance, total (années)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(42,41,\'Prévalence de la malnutrition, poids selon l’âge (% des enfants de mois de 5 ans)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(43,44,\'Taux de mortalité infantile (pour 1 000 naissances vivantes)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(44,45,\'Taux de mortalité infantile, moins de 5 ans (pour 1 000)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(45,42,\'Prévalence du VIH, total (% de la population âgée de 15 à 49 ans)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(46,46,\'Taux d’achèvement de l’école primaire, total (% du groupe d’âge pertinent)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(47,47,\'Rapport de parité filles-garçons dans les écoles primaires et secondaires (%)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(48,48,\'Utilisation des crédits du FMI (Dette en cours et décaissée, $ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(49,49,\'Chercheurs en recherche et développement (pour un million de personnes)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(50,50,\'Exportations de haute technologie (% des exportations de biens manufacturés)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(51,51,\'Utilisateurs Internet\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(52,52,\'Utilisateurs Internet (pour 100 personnes)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(53,54,\'Capitalisation boursière des sociétés cotées (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(54,55,\'Dépenses militaires (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(55,56,\'Dépenses en santé, total (% du PIB)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(56,57,\'Dépenses en santé par habitant ($ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(57,53,\'Abonnés à la téléphonie mobile (pour 100 personnes)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(58,58,\'Routes, pavées (% des routes totales)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(59,59,\'Temps nécessaire pour démarrer une entreprise (jours)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(60,60,\'RNB par habitant, ($ PPA internationaux courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(61,61,\'RNB par habitant, méthode Atlas (en $ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(62,62,\'RNB, méthode Atlas (en $ US courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(63,63,\'RNB, ($ PPA internationaux courants)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(64,64,\'Croissance de la population (% annuel)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(65,65,\'Population, total\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(66,66,\'Densité de la population (nombre de personne par km carré)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(67,67,\'Ratio de la population pauvre en fonction du seuil de pauvreté national (% de la population rurale)\')');
fr_db_queries.push('INSERT INTO "fr_indicator_name_tbl" VALUES(68,68,\'Superficie (kilomètres carrés)\')');
fr_db_queries.push('CREATE TABLE fr_category_name_tbl (  id INTEGER,  category_id INTEGER UNIQUE,  category_name VARCHAR NOT NULL UNIQUE,   PRIMARY KEY (id))');
fr_db_queries.push('INSERT INTO "fr_category_name_tbl" VALUES(1,1,\'Economie\')');
fr_db_queries.push('INSERT INTO "fr_category_name_tbl" VALUES(2,2,\'Environnement\')');
fr_db_queries.push('INSERT INTO "fr_category_name_tbl" VALUES(3,3,\'Tendances mondiales\')');
fr_db_queries.push('INSERT INTO "fr_category_name_tbl" VALUES(4,4,\'Populations\')');
fr_db_queries.push('INSERT INTO "fr_category_name_tbl" VALUES(5,5,\'Etats et marchés\')');
fr_db_queries.push('INSERT INTO "fr_category_name_tbl" VALUES(6,6,\'Vision du monde\')');
fr_db_queries.push('INSERT INTO "fr_category_name_tbl" VALUES(7,7,\'Autre\')');
